package scripting;
import java.*;
import java.io.*;
import java.text.*;
import java.time.*;
import java.util.*;
import java.util.stream.*;
import java.util.function.*;
import java.util.regex.*;
/**
 * This class was automatically generated by the VoogaJavaEngine. It contains user written scripts, and is dynamically compiled at runtime.
 *
 * @author th174
 */
public class VoogaJavaEngine_generated_source$1 {
	public static Object voogaFunction(backend.player.Team team, backend.util.AuthoringGameState gameState) {
		gameState.getActiveTeam().getOwnedUnits(gameState.getGrid()).stream()
		.filter(unit -> (unit.getCurrentCell().getOccupants().size() > 1))
		.filter(un -> !un.getTeam().equals(team))
		.forEach(u -> u.getCurrentCell().removeOccupants(u));
		
		return gameState;
	}
}