package scripting;
import java.*;
import java.io.*;
import java.text.*;
import java.time.*;
import java.util.*;
import java.util.stream.*;
import java.util.function.*;
import java.util.regex.*;
/**
 * This class was automatically generated by the VoogaJavaEngine. It contains user written scripts, and is dynamically compiled at runtime.
 *
 * @author th174
 */
public class VoogaJavaEngine_generated_source$15 {
	public static Object voogaFunction(backend.unit.ModifiableUnit user, backend.unit.ModifiableUnit target, backend.util.AuthoringGameState gameState) {
		ArrayList<backend.unit.Unit> units = new ArrayList<>(gameState.getGrid().get(target.getLocation()).getOccupants());
		units.forEach(e -> e.takeDamage(10000));
		user.moveTo(gameState.getGrid().get(target.getLocation()),gameState);
		
		return null;
	}
}